services:
  - type: web
    name: duct-vendor-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade  # ✅ This runs your Alembic migrations
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: duct-vendor-db
          property: connectionString

databases:
  - name: duct-vendor-db
